// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Rpl6x-Ni0QNWT-asG-CfOvewMkaYkaQ',
    appId: '1:504572446517:web:27dbd95fc1655003a52e7c',
    messagingSenderId: '504572446517',
    projectId: 'fir-tuto-9682f',
    authDomain: 'fir-tuto-9682f.firebaseapp.com',
    storageBucket: 'fir-tuto-9682f.appspot.com',
    measurementId: 'G-JRDP1N1WWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpbWVctVfuwTaG-OR5nKEMEVBWSVaN2Ms',
    appId: '1:504572446517:android:c8919036ef0c793da52e7c',
    messagingSenderId: '504572446517',
    projectId: 'fir-tuto-9682f',
    storageBucket: 'fir-tuto-9682f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ynjego_hqBbNRIlCBEYpvYsrpdXCVwo',
    appId: '1:504572446517:ios:36be89533a37101ba52e7c',
    messagingSenderId: '504572446517',
    projectId: 'fir-tuto-9682f',
    storageBucket: 'fir-tuto-9682f.appspot.com',
    iosClientId: '504572446517-gfqfjqe4p7uhmhomg8g4jk96on4sjnp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaesTuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ynjego_hqBbNRIlCBEYpvYsrpdXCVwo',
    appId: '1:504572446517:ios:36be89533a37101ba52e7c',
    messagingSenderId: '504572446517',
    projectId: 'fir-tuto-9682f',
    storageBucket: 'fir-tuto-9682f.appspot.com',
    iosClientId: '504572446517-gfqfjqe4p7uhmhomg8g4jk96on4sjnp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaesTuto',
  );
}
